Description:
  Olamide Adesoba / Udacity
  This template deploys a servers and its assocated resources e.g security groups.


Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String


  imageid:
    Description: Please enter the image id
    Type: String

  keyname:
    Description: Please enter the keyname
    Type: String


Resources:
  ServerInstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Roles: 
        - UdacityServerRole

  WebServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our hosts and SSH from local only
      VpcId: 
        Fn::ImportValue:
          !Sub '${EnvironmentName}-VpcID'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName      

  Ec2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref imageid
      IamInstanceProfile: !Ref ServerInstanceProfile
      InstanceType: t3.medium
      KeyName: 
        Ref: "keyname"
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
            - Ref: "WebServerSecGroup"
          SubnetId: 
            Fn::ImportValue:
              !Sub '${EnvironmentName}-PublicSubnetID'


Outputs:
  PublicIp:
    Description: Server Public IP
    Value: !GetAtt Ec2Instance.PublicIp
    Export:
      Name: !Sub "PublicIp"

  PublicDnsName:
    Description: Server PublicDnsName
    Value: !GetAtt Ec2Instance.PublicDnsName
    Export:
      Name: !Sub "PublicDnsName"
