
version: 2.1


jobs:
  create_network_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create network Stack
          command: |
            aws configure list
            
            aws configure set aws_session_token $AWS_Session_Token 
            
            cd .. | sh create.sh MideNetwork network.yml network-parameters.json
            

   


workflows:
  infrastructure provisioning:
    jobs:
      - create_network_infrastructure
   