
version: 2.1


jobs:
  create_network_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create network Stack
          command: |
            cd ..
            sh create.sh MideNetwork network.yaml network-parameters.json

   


workflows:
  infrastructure provisioning:
    jobs:
      - create_network_infrastructure
   