
version: 2.1


jobs:
  print-hello:
   
    docker:
      - image: circleci/node:13.8.0

    steps:
      - run: echo hello

  print-name:
   
    docker:
      - image: circleci/node:13.8.0

    steps:
      - run: echo $NAME
   


workflows:
  say-hello-workflow:
    jobs:
      - print-hello
      - print-name:
          requires:
            - print-hello