
version: 2.1


orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  create_network_infrastructure: 
    docker:
      - image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - run:
          name: Create network Stack
          command: |
            
            export AWS_PROFILE=udacity
            aws configure set aws_session_token $AWS_Session_Token 
            aws configure list
            
            
            cd .. | sh create.sh MideNetwork network.yml network-parameters.json
            

   


workflows:
  infrastructure provisioning:
    jobs:
      - create_network_infrastructure
   